// IMPORTANT: Do not edit this file without first reading project-management/development_practices.md for ExanimaTools best practices.
// Ensure all logging uses injected ILoggingService.

using Avalonia.Controls;
using Avalonia.Input;

namespace ExanimaTools.Controls
{
    public partial class PipDisplayControl : UserControl
    {
        public PipDisplayControl()
        {
            InitializeComponent();
            this.DataContextChanged += (s, e) => {
                var vm = this.DataContext;
                if (vm != null)
                {
                    App.LoggingServiceInstance?.LogOperation("PipDisplayControl.DataContextChanged", $"New DataContext: {vm.GetType().Name}");
                }
                else
                {
                    App.LoggingServiceInstance?.LogOperation("PipDisplayControl.DataContextChanged", "New DataContext: null");
                }
            };
        }

        private void PipHalf_PointerPressed(object? sender, PointerPressedEventArgs e)
        {
            // TODO: Implement logic to set pip to half (or call ViewModel)
        }

        private void PipFull_PointerPressed(object? sender, PointerPressedEventArgs e)
        {
            // TODO: Implement logic to set pip to full (or call ViewModel)
        }
    }
}
