// IMPORTANT: Do not edit this file without first reading project-management/development_practices.md for ExanimaTools best practices.
// Ensure all logging uses injected ILoggingService.

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;

namespace ExanimaTools.Models
{
    public enum EquipmentQuality
    {
        Poor,
        Common,
        WellMade,
        Masterwork,
        Legendary
    }

    public enum EquipmentCondition
    {
        Ruined,
        Damaged,
        Worn,
        Fair,
        Used,
        Good,
        Excellent,
        Pristine
    }

    public class EquipmentPiece : INotifyPropertyChanged
    {
        /// <summary>
        /// Unique database key for this equipment item.
        /// </summary>
        public int Id { get; set; } // Unique DB key

        private readonly ILoggingService? _logger;
        public EquipmentPiece(ILoggingService? logger = null)
        {
            _logger = logger;
            _logger?.LogOperation("Create EquipmentPiece", $"Name={_name}");
        }
        private string _name = string.Empty;
        public string Name
        {
            get => _name;
            set { _name = value; _logger?.LogOperation("Set Name", value); }
        }
        private EquipmentType _type;
        public EquipmentType Type
        {
            get => _type;
            set { if (!EqualityComparer<EquipmentType>.Default.Equals(_type, value)) { _type = value; OnPropertyChanged(nameof(Type)); } }
        }
        public EquipmentSlot Slot { get; set; }
        public ArmourLayer? Layer { get; set; }
        private Dictionary<StatType, float> _stats = new();
        public Dictionary<StatType, float> Stats
        {
            get => _stats;
            set
            {
                _stats = value.ToDictionary(kv => kv.Key, kv => Math.Clamp(kv.Value, 0, 10));
                _logger?.LogOperation("Set Stats", string.Join(",", _stats.Select(kv => $"{kv.Key}:{kv.Value}")));
            }
        }
        public string Description { get; set; } = string.Empty;
        public EquipmentQuality Quality { get; set; } = EquipmentQuality.Common;
        public EquipmentCondition Condition { get; set; } = EquipmentCondition.Good;
        private string _category = string.Empty;
        public string Category
        {
            get => _category;
            set { if (_category != value) { _category = value; OnPropertyChanged(nameof(Category)); } }
        }
        public string Subcategory { get; set; } = string.Empty; // e.g., "Swords", "Polearms", "Body", "Head"
        public Rank Rank { get; set; } = Rank.Novice; // Minimum required rank to equip
        public int Points { get; set; } = 0; // Loadout cost
        public float Weight
        {
            get => Stats.TryGetValue(StatType.Weight, out var w) ? w : 0f;
            set => SetStat(StatType.Weight, value);
        }
        public void SetStat(StatType stat, float value)
        {
            float clamped = Math.Clamp(value, 0, 10);
            _stats[stat] = clamped;
            _logger?.LogOperation("Set Stat", $"{stat}={clamped}");
        }

        private string? _imagePath;
        public string? ImagePath
        {
            get => _imagePath;
            set { if (_imagePath != value) { _imagePath = value; OnPropertyChanged(nameof(ImagePath)); } }
        }

        // Returns a list of pip stat view models for this equipment (for stat card display)
        public List<object> GetPipStatsViewModels()
        {
            var pipStats = new List<object>();
            var vmType = System.Reflection.Assembly.Load("ExanimaToolsApp").GetType("ExanimaTools.ViewModels.StatPipViewModel");
            if (vmType == null) return pipStats;
            var ctor = vmType.GetConstructor(new[] { typeof(StatType), typeof(float), typeof(Action<float>), typeof(object) });
            foreach (var kvp in Stats)
            {
                if (kvp.Key == StatType.Weight) continue;
                if (IsPipStat(kvp.Key) && ctor != null)
                {
                    var vm = ctor.Invoke(new object[] { kvp.Key, kvp.Value, (Action<float>)(v => SetStat(kvp.Key, v)), null! });
                    pipStats.Add(vm);
                }
            }
            return pipStats;
        }

        // Helper: which stats are pip stats (should match add form logic)
        public static bool IsPipStat(StatType stat)
        {
            return stat == StatType.Balance || stat == StatType.Impact || stat == StatType.Slash || stat == StatType.Crush ||
                   stat == StatType.Pierce || stat == StatType.Thrust || stat == StatType.Points ||
                   stat == StatType.SlashProtection || stat == StatType.CrushProtection || stat == StatType.PierceProtection ||
                   stat == StatType.Coverage || stat == StatType.Encumbrance;
        }

        public event PropertyChangedEventHandler? PropertyChanged;
        protected void OnPropertyChanged(string propertyName) => PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }
}
