// IMPORTANT: Do not edit this file without first reading project-management/development_practices.md for ExanimaTools best practices.
// Ensure all logging uses injected ILoggingService.

using Avalonia.Controls;
using ExanimaTools.Models;
using ExanimaTools.ViewModels;

namespace ExanimaTools.Controls
{
    public partial class EquipmentStatCardControl : UserControl
    {
        public EquipmentStatCardControl()
        {
            InitializeComponent();
            this.DataContextChanged += (s, e) => {
                var vm = this.DataContext;
                if (vm != null)
                {
                    App.LoggingServiceInstance?.LogOperation("EquipmentStatCardControl.DataContextChanged", $"New DataContext: {vm.GetType().Name}");
                }
                else
                {
                    App.LoggingServiceInstance?.LogOperation("EquipmentStatCardControl.DataContextChanged", "New DataContext: null");
                }
            };
        }
    }
}
