// IMPORTANT: Do not edit this file without first reading project-management/development_practices.md for ExanimaTools best practices.
// Ensure all logging uses injected ILoggingService.

using Avalonia.Controls;

namespace ExanimaTools.Controls
{
    public partial class EquipmentManagerControl : UserControl
    {
        public EquipmentManagerControl()
        {
            InitializeComponent();
            // Inject the global logger into the viewmodel for full debug logging
            var vm = new ExanimaTools.ViewModels.EquipmentManagerViewModel(App.LoggingServiceInstance);
            this.DataContext = vm;
            App.LoggingServiceInstance?.LogOperation("EquipmentManagerControl.DataContextSet", $"DataContext set to {vm.GetType().Name}");
        }
    }
}
